apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: svcnex-dags-prod
  description: ""
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/servicenex-airflow-dags
    backstage.io/source-vcs: Github
    google.com/cloudbuild-trigger-name: cb-svcnex-dags-prod-prod
    google.com/cloudbuild-project-slug: ivedha-mgmt-env-prod
    google.com/cloudbuild-location: us-central1
    google.com/gcp-projectid: ""
spec:
  type: service
  lifecycle: production
  owner: group:default/servicenex-admin
  system: system:default/servicenex
  dependsOn: []
  dependencyOf: []
  annotations:
    backstage.io/source-location: https://github.com/ivedha-tech/servicenex-airflow-dags
    backstage.io/source-vcs: github
